### ISSUE TITLE
Swagger apiPath issue

### ISSUE THREAD

**Issue by mmenik** [tsmean/tsmean#7] opened 2018-03-21 13:34 UTC
When use swagger all router url have concatenated 2 time /api/1/

**Comment by MichalLytek** [comment] 2018-03-21 13:51
You're right, the problem is with [this line](https://github.com/tsmean/tsmean/blob/master/backend/src/server.ts#L27). I will take a look why I've put it here 😉

**Comment by MichalLytek** [comment] 2018-03-23 10:10
I'm not able to reproduce the error, in swagger ui all looks good:
![image](https://user-images.githubusercontent.com/10618781/37823729-a4976e4e-2e8a-11e8-867a-f218cf02c882.png)

And in http it's also ok:
`http://localhost:4242/api/v1/animal-lists`
```js
{"data":[{"id":1,"name":"Public"}]}
```

**Comment by mmenik** [comment] 2018-03-23 10:54
But you changed something? I have the issue

![swagger](https://user-images.githubusercontent.com/25682572/37825679-f794c49c-2e90-11e8-8cac-28475feebf91.jpg)

**Comment by MichalLytek** [comment] 2018-03-23 14:04
Ok, now I get it 😉 Fixed in https://github.com/tsmean/tsmean/commit/29771cbecc3ef6043e29c4a64a92746e0052c35f

**Closed as completed by MichalLytek** 2018-03-23 14:04 UTC
Labels: question
